### ISSUE TITLE
Mozilla Public License in Makefile

### ISSUE THREAD

**Issue by thernstig** [TritonDataCenter/node-assert-plus#44]
https://github.com/joyent/node-assert-plus/blob/00200d6a95eb1dbe643546a3cab8494d3fc47a0e/Makefile#L1-L9

What does this part mean there? Why would a Makefile be under the Mozilla Public License (MPL) license. I have never seen a Makefile mention that before so it's unclear what this means.

If that is true how come it is not in the LICENSE file?

**Comment by bahamat** [comment]
Most things we (as an organization) publish are under MPL, but this repo, in its entirety, should be MIT. Thanks for pointing this out, I'll et it fixed.

**Comment by thernstig** [comment]
@bahamat thanks for the reply. As in _fixed_ here, you mean that part in the Makefile will be removed in a new commit/version?

So only MIT will the only license for this repo?

**Comment by bahamat** [comment]
That’s correct. See #45.

The code in this repo is licensed under the MIT license terms as per the LICENSE file. Any reference to other license terms is incorrect.

**Comment by bahamat** [comment]
Fixed in #45
